// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using todo_mvc_csharp_problem_sankalpjohri.Connectors;

namespace todomvccsharpproblemsankalpjohri.Migrations
{
    [DbContext(typeof(NotesContext))]
    [Migration("20180802071359_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("todo_mvc_csharp_problem_sankalpjohri.Entities.ChecklistItem", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("isChecked");

                    b.Property<long>("noteId");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.ToTable("ChecklistItems");
                });

            modelBuilder.Entity("todo_mvc_csharp_problem_sankalpjohri.Entities.Label", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("noteId");

                    b.Property<string>("text");

                    b.HasKey("id");

                    b.ToTable("labels");
                });

            modelBuilder.Entity("todo_mvc_csharp_problem_sankalpjohri.Entities.Note", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("isPinned");

                    b.Property<string>("text");

                    b.Property<string>("title")
                        .IsRequired();

                    b.HasKey("id");

                    b.ToTable("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
