version: "3.1"
services:
    web:
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - mongo
    mongo:
      image: mongo:4.1
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: sankalp
        MONGO_INITDB_ROOT_PASSWORD: test123
        MONGO_INITDB_DATABASE: NoteDB
      ports:
        - "27017:27017"