version: "3"
services:
    web:
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - mongo
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: sankalp
            MONGO_INITDB_ROOT_PASSWORD: test@123